typography_spectrum: 0.12984
color:
  brandColors:
    - '#cdccc8'
    - '#c59d2d'
    - '#08173e'
    - '#756d6a'
    - '#30588a'
  brandStrength: 0.7132468644995242
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: benhutchinson
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
