name: benhutchinson
favicon: null
layout_spectrum: 0.6414723074994981
typography_spectrum: 0.95358
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cdccc8'
    - '#c59d2d'
    - '#08173e'
    - '#756d6a'
    - '#30588a'
  brandStrength: 0.7132468644995242
  lightness: 1
  saturation: 0.0625
  rhythmicContrast: 0.25
purpose: []
