name: benhutchinson
favicon: null
layout_spectrum: 0.6414723074994981
typography_spectrum: 0.5685749396216124
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7132468644995242
  lightness: 0.22186688263900578
  saturation: 0.29769363603554666
  rhythmicContrast: 0.6364113229792565
purpose: []
